//! The single point of contact with C.
//!
//! Every C header the project needs is included in ONE `@cImport` block, and the
//! rest of the codebase reaches C types only through `@import("c.zig").c`.
//!
//! This is not stylistic. Each `@cImport` block produces its own independent set
//! of Zig types, so `struct_wl_surface` translated in two different blocks are two
//! *incompatible* types despite being the same C struct. Splitting the imports
//! across modules produces type errors that read as though the compiler has lost
//! its mind. One block, always.
//!
//! (`pub usingnamespace` would let callers import these names flat, but it was
//! removed in Zig 0.16, hence the explicit `.c` qualifier everywhere.)

pub const c = @cImport({
    // Core Wayland client. Pulls in wayland-client-protocol.h (shipped by
    // libwayland-dev) for the wl_* interfaces.
    @cInclude("wayland-client.h");
    // wl_egl_window: binds a wl_surface to an EGL native window.
    @cInclude("wayland-egl.h");

    // Generated by wayland-scanner in build.zig. Names match the output basenames
    // chosen there, not upstream's conventional filenames.
    @cInclude("xdg-shell-client-protocol.h");
    @cInclude("xdg-decoration-client-protocol.h");

    @cInclude("EGL/egl.h");
    @cInclude("GLES3/gl3.h");
});
